/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false packages/hosted/worker-configuration.d.ts` (hash: 6af8dc9579d380b3af59c90ed42122ee)
interface __BaseEnv_Env {
	DB: D1Database;
	EMAIL: SendEmail;
	PUBLIC_RATE_LIMIT: RateLimit;
	APP_ORIGIN: string;
	SIGNUPS_ENABLED: string;
	BILLING_ENABLED: string;
	CURRENCY: string;
	WORKSPACES: DurableObjectNamespace<import("./src/index").Workspace>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "Workspace";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "SIGNUPS_ENABLED" | "BILLING_ENABLED" | "CURRENCY">> {}
}
