#!/usr/bin/env bash
#
# Keeps the PairLobby relay running in the background.
#
# On macOS this installs a LaunchAgent, which is the part a shell hook cannot do:
# it starts at login without a terminal open, restarts the relay if it dies, and
# costs nothing on every new shell. The shell-hook alternative is documented in
# the README for anyone who would rather not install an agent.

set -euo pipefail

LABEL="com.pairlobby.relay"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
SUPPORT="$HOME/Library/Application Support/PairLobby"
LOGS="$HOME/Library/Logs/PairLobby"
LAUNCHER="$SUPPORT/relay-launch.sh"
PORT="${PAIRLOBBY_PORT:-8790}"
HOST="${PAIRLOBBY_HOST:-127.0.0.1}"

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CLI="$REPO/packages/cli/dist/main.js"

die() { printf '%s\n' "$*" >&2; exit 1; }
note() { printf '%s\n' "$*"; }

require_macos() {
    [ "$(uname -s)" = "Darwin" ] || die "This installs a macOS LaunchAgent. On Linux use a systemd --user unit, or the shell hook in the README."
}

relay_responds() {
    command -v curl >/dev/null 2>&1 || return 1
    # Retried briefly: asking in the second between a restart and the port being
    # bound would otherwise report a healthy relay as down.
    local attempt code
    for attempt in 1 2 3; do
        code=0
        curl -fsS -o /dev/null -m 2 "http://$HOST:$PORT/v1/rooms" 2>/dev/null || code=$?
        # 7 is "connection refused". Any HTTP reply, including the 404 this path
        # returns, means something is listening and speaking the protocol.
        [ "$code" -ne 7 ] && return 0
        [ "$attempt" -lt 3 ] && sleep 1
    done
    return 1
}

cmd_install() {
    require_macos
    [ -f "$CLI" ] || die "Build first: npm run build"
    NODE="$(command -v node)" || die "node is not on PATH"

    mkdir -p "$SUPPORT" "$LOGS" "$HOME/Library/LaunchAgents"

    # A wrapper rather than putting node's path straight in the plist: node moves
    # when you switch versions, and one file to regenerate beats editing XML.
    cat > "$LAUNCHER" <<EOF
#!/bin/sh
# Generated by scripts/relay-service.sh. Re-run "install" after changing node version.
exec "$NODE" "$CLI" serve --host "$HOST" --port "$PORT"
EOF
    chmod +x "$LAUNCHER"

    cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key><string>$LABEL</string>
    <key>ProgramArguments</key>
    <array><string>$LAUNCHER</string></array>
    <key>RunAtLoad</key><true/>
    <key>KeepAlive</key>
    <dict><key>SuccessfulExit</key><false/></dict>
    <!-- Without this, a port clash becomes a restart loop several times a second. -->
    <key>ThrottleInterval</key><integer>10</integer>
    <key>StandardOutPath</key><string>$LOGS/relay.log</string>
    <key>StandardErrorPath</key><string>$LOGS/relay.log</string>
    <key>ProcessType</key><string>Background</string>
</dict>
</plist>
EOF

    launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true
    launchctl bootstrap "gui/$(id -u)" "$PLIST"

    note "Installed $LABEL"
    note "  relay   http://$HOST:$PORT"
    note "  logs    $LOGS/relay.log"
    note "  plist   $PLIST"
    note ""
    note "It starts at login and restarts if it stops. Check it with:"
    note "  $0 status"
}

cmd_uninstall() {
    require_macos
    launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true
    rm -f "$PLIST" "$LAUNCHER"
    note "Removed $LABEL. Rooms and credentials are untouched in $SUPPORT."
}

cmd_status() {
    if launchctl print "gui/$(id -u)/$LABEL" >/dev/null 2>&1; then
        note "agent   loaded"
    else
        note "agent   not installed"
    fi
    if relay_responds; then
        note "relay   answering on http://$HOST:$PORT"
    else
        note "relay   not answering on http://$HOST:$PORT"
        note "        last lines of $LOGS/relay.log:"
        tail -n 5 "$LOGS/relay.log" 2>/dev/null | sed 's/^/        /' || note "        (no log yet)"
    fi
}

cmd_restart() {
    require_macos
    launchctl kickstart -k "gui/$(id -u)/$LABEL"
    note "restarted"
}

cmd_logs() { tail -f "$LOGS/relay.log"; }

case "${1:-}" in
    install)   cmd_install ;;
    uninstall) cmd_uninstall ;;
    status)    cmd_status ;;
    restart)   cmd_restart ;;
    logs)      cmd_logs ;;
    *) die "usage: $0 {install|uninstall|status|restart|logs}" ;;
esac
