# Keeps the PairLobby relay running in the background on Windows.
#
# The macOS counterpart uses a LaunchAgent; the equivalent here is a per-user
# scheduled task triggered at logon, with a restart policy standing in for
# launchd's KeepAlive. No administrator rights and no service wrapper needed.
#
#   powershell -ExecutionPolicy Bypass -File scripts\relay-service.ps1 install

[CmdletBinding()]
param(
    [Parameter(Position = 0)]
    [ValidateSet('install', 'uninstall', 'status', 'restart', 'logs')]
    [string]$Command = 'status'
)

$ErrorActionPreference = 'Stop'

$TaskName = 'PairLobby Relay'
$Repo     = Split-Path -Parent $PSScriptRoot
$Cli      = Join-Path $Repo 'packages\cli\dist\main.js'
$Support  = Join-Path $env:APPDATA 'PairLobby'
$LogDir   = Join-Path $env:LOCALAPPDATA 'PairLobby\logs'
$LogFile  = Join-Path $LogDir 'relay.log'
$Launcher = Join-Path $Support 'relay-launch.vbs'
$RelayHost = if ($env:PAIRLOBBY_HOST) {$env:PAIRLOBBY_HOST} else {'127.0.0.1'}
$Port      = if ($env:PAIRLOBBY_PORT) {$env:PAIRLOBBY_PORT} else {'8790'}

function Test-Relay {
    # Any HTTP reply means something is listening; this path answers 404, which
    # still tells us the relay is up. Retried because a just-restarted task may
    # not have bound the port yet.
    foreach ($attempt in 1..3) {
        try {
            Invoke-WebRequest -Uri "http://${RelayHost}:$Port/v1/rooms" -TimeoutSec 2 -UseBasicParsing | Out-Null
            return $true
        } catch [System.Net.WebException] {
            if ($_.Exception.Response) {return $true}
        } catch {
            if ($_.Exception.Response) {return $true}
        }
        if ($attempt -lt 3) {Start-Sleep -Seconds 1}
    }
    return $false
}

function Invoke-Install {
    if (-not (Test-Path $Cli)) {throw "Build first: npm run build"}
    $node = (Get-Command node -ErrorAction SilentlyContinue).Source
    if (-not $node) {throw 'node is not on PATH'}

    New-Item -ItemType Directory -Force -Path $Support, $LogDir | Out-Null

    # A VBScript shim because Windows has no windowless node: run it with window
    # style 0 or every logon flashes a console. Regenerate after changing node
    # version, since its path is baked in here.
    $vbs = @"
' Generated by scripts\relay-service.ps1. Re-run "install" after changing node version.
Set shell = CreateObject("WScript.Shell")
cmd = """$node"" ""$Cli"" serve --host $RelayHost --port $Port"
shell.Run "cmd /c " & cmd & " >> ""$LogFile"" 2>&1", 0, False
"@
    Set-Content -Path $Launcher -Value $vbs -Encoding ASCII

    $action  = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument "`"$Launcher`""
    # No -User: it wants a fully-qualified principal and the format differs
    # between domain-joined and standalone machines. Register-ScheduledTask
    # defaults to the current user, which is what we want anyway.
    $trigger = New-ScheduledTaskTrigger -AtLogOn
    $settings = New-ScheduledTaskSettingsSet `
        -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable `
        -MultipleInstances IgnoreNew `
        -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1) `
        -ExecutionTimeLimit ([TimeSpan]::Zero)

    Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
        -Settings $settings -Description 'PairLobby relay' -Force | Out-Null
    Start-ScheduledTask -TaskName $TaskName

    Write-Host "Installed scheduled task '$TaskName'"
    Write-Host "  relay   http://${RelayHost}:$Port"
    Write-Host "  logs    $LogFile"
    Write-Host ''
    Write-Host 'It starts at logon and restarts if it stops. Check it with:'
    Write-Host '  npm run service:status'
}

function Invoke-Uninstall {
    if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
        Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
    }
    Remove-Item $Launcher -ErrorAction SilentlyContinue
    Write-Host "Removed '$TaskName'. Rooms and credentials are untouched in $Support."
}

function Invoke-Status {
    $task = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    if ($task) {
        Write-Host "task    registered ($($task.State))"
    } else {
        Write-Host 'task    not installed'
    }
    if (Test-Relay) {
        Write-Host "relay   answering on http://${RelayHost}:$Port"
    } else {
        Write-Host "relay   not answering on http://${RelayHost}:$Port"
        Write-Host "        last lines of ${LogFile}:"
        if (Test-Path $LogFile) {
            Get-Content $LogFile -Tail 5 | ForEach-Object {Write-Host "        $_"}
        } else {
            Write-Host '        (no log yet)'
        }
    }
}

switch ($Command) {
    'install'   {Invoke-Install}
    'uninstall' {Invoke-Uninstall}
    'status'    {Invoke-Status}
    'restart'   {Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue; Start-ScheduledTask -TaskName $TaskName; Write-Host 'restarted'}
    'logs'      {if (Test-Path $LogFile) {Get-Content $LogFile -Wait -Tail 20} else {Write-Host "no log at $LogFile"}}
}
