import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {mkdtempSync, rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join, resolve} from 'node:path';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {z} from 'zod';
import {expect, test, vi} from 'vitest';
import {LocalStore, PairLobbyClient} from '@pairlobby/client';
import {newId} from '@pairlobby/protocol';
import {startServer} from '@pairlobby/local-server';
import {waitForReply} from '../src/reply-wait.js';

const execute = promisify(execFile);
const cliPath = process.env['PAIRLOBBY_TEST_CLI'] ?? resolve('packages/cli/dist/main.js');
type ChannelNotice = {content: string; meta: Record<string, string>};

test('real channel resumes only an explicitly watched reply, respects pause, and acknowledges durable continuation', async () => {
    const directory = mkdtempSync(join(tmpdir(), 'reply-channel-'));
    const relay = await startServer({port: 0, dataFile: join(directory, 'relay.sqlite')});
    const api = new PairLobbyClient(relay.url);
    const own = await api.createRoom('reply continuation', {displayName: 'origin', kind: 'agent'});
    const peer = await api.redeemInvite(own.invite.code, {displayName: 'peer', kind: 'human'});
    const sessionId = newId('session');
    const store = new LocalStore(join(directory, 'device'));
    store.upsertRoom({roomId: own.roomId, name: 'reply continuation', serverUrl: relay.url, createdAt: Date.now(), expiresAt: null, controls: false, sessions: []});
    store.addSession(own.roomId, {sessionId, participantId: own.participantId, displayName: 'origin', kind: 'agent', role: 'member', joinedAt: Date.now(), lastReadSeq: 0, cwd: directory});
    store.putCredential(own.roomId, sessionId, own.participantCredential);
    const notices: ChannelNotice[] = [];
    const mcp = new Client({name: 'reply-test', version: '1'});
    mcp.setNotificationHandler(z.object({method: z.literal('notifications/claude/channel'), params: z.object({content: z.string(), meta: z.record(z.string())})}), (notice) => { notices.push(notice.params); });
    const send = async (text: string) => (await api.send(own.roomId, own.participantCredential, {type: 'message', recipientId: peer.participantId, payload: {text, priority: 'normal'}, idempotencyKey: newId('event')})).event.eventId;
    const watch = (eventId: string) => mcp.callTool({name: 'watch_reply', arguments: {eventId}});
    const replies = () => notices.filter((notice) => notice.meta['kind'] === 'reply_ready');
    try {
        await mcp.connect(new StdioClientTransport({command: process.execPath, args: [cliPath, 'channel', '--room', own.roomId, '--session', sessionId, '--allow-from', peer.participantId], env: {PAIRLOBBY_DATA_DIR: store.directory}, stderr: 'pipe'}));
        const awaited = await send('Need this result');
        expect((await watch(awaited)).isError).not.toBe(true);
        expect((await watch(awaited)).isError).not.toBe(true);
        const unrelated = await send('Different task');
        await api.reply(own.roomId, peer.participantCredential, unrelated, 'Unrelated result');
        await api.reply(own.roomId, peer.participantCredential, awaited, 'Working on it', true);
        const bounded = await execute(process.execPath, [cliPath, 'wait-reply', awaited, '--room', own.roomId, '--session', sessionId, '--wait', '0.2', '--json'], {env: {...process.env, PAIRLOBBY_DATA_DIR: store.directory}});
        expect(JSON.parse(bounded.stdout)).toMatchObject({state: 'pending', retryable: true});
        expect(replies()).toHaveLength(0);
        expect((await api.request(own.roomId, own.participantCredential, awaited)).failureAt).toBeFalsy();
        await api.control(own.roomId, own.controllerCredential, own.participantId, true);
        await vi.waitFor(() => expect(notices.some((notice) => notice.content.includes('requested pause'))).toBe(true));
        await api.reply(own.roomId, peer.participantCredential, awaited, 'The exact final result');
        const result = await waitForReply({serverUrl: relay.url, roomId: own.roomId, credential: own.participantCredential, participantId: own.participantId, requestId: awaited, seconds: 0});
        expect(result).toMatchObject({state: 'answered', text: 'The exact final result'});
        expect(replies()).toHaveLength(0);
        await api.control(own.roomId, own.controllerCredential, own.participantId, false);
        await vi.waitFor(() => expect(replies()).toHaveLength(1), {timeout: 5000});
        expect(replies()[0]?.meta['event_id']).toBe(awaited);
        expect(replies()[0]?.content).toContain('The exact final result');
        expect((await mcp.callTool({name: 'complete_reply_watch', arguments: {eventId: awaited}})).isError).not.toBe(true);
        const cancelled = await send('Superseded question');
        await watch(cancelled);
        expect((await mcp.callTool({name: 'cancel_reply_watch', arguments: {eventId: cancelled}})).isError).not.toBe(true);
        await api.reply(own.roomId, peer.participantCredential, cancelled, 'Late result');
        const already = await send('Already answered before watching');
        await api.reply(own.roomId, peer.participantCredential, already, 'Recovered without replaying the transcript');
        await watch(already);
        await vi.waitFor(() => expect(replies()).toHaveLength(2), {timeout: 5000});
        expect(replies().map((notice) => notice.meta['event_id'])).toEqual([awaited, already]);
        const parent = await api.send(own.roomId, peer.participantCredential, {type: 'message', recipientId: own.participantId, payload: {text: 'Original task needing another answer', priority: 'normal'}, idempotencyKey: newId('event')});
        const dependency = await send('Dependency for original task');
        const registered = await mcp.callTool({name: 'watch_reply', arguments: {eventId: dependency, parentEventId: parent.event.eventId}});
        expect(registered.isError).not.toBe(true);
        const hook = await new Promise<string>((done, reject) => {
            const child = execFile(process.execPath, [cliPath, 'guard-stop', '--room', own.roomId, '--session', sessionId], {env: {...process.env, PAIRLOBBY_DATA_DIR: store.directory}}, (error, stdout) => error ? reject(error) : done(stdout));
            child.stdin!.end(JSON.stringify({stop_hook_active: true}));
        });
        expect(JSON.parse(hook)).toEqual({});
        expect((await api.request(own.roomId, own.participantCredential, parent.event.eventId)).failureAt).toBeFalsy();
        await api.reply(own.roomId, peer.participantCredential, dependency, 'Dependency complete');
        await vi.waitFor(() => expect(replies()).toHaveLength(3), {timeout: 5000});
        expect(replies()[2]?.meta['parent_event_id']).toBe(parent.event.eventId);
        expect((await mcp.callTool({name: 'reply_to_message', arguments: {eventId: parent.event.eventId, text: 'Original task finished using the dependency'}})).isError).not.toBe(true);
        await mcp.callTool({name: 'complete_reply_watch', arguments: {eventId: dependency}});
        expect(store.room(own.roomId)?.sessions[0]?.lastReadSeq).toBe(0);
    } finally {
        await mcp.close();
        await relay.close();
        rmSync(directory, {recursive: true, force: true});
    }
}, 20_000);
